/**
 * (C) Copyright IBM Corp. 2020.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Package exampleservicev1 : Operations and models for the ExampleServiceV1 service
package exampleservicev1

import (
	"encoding/json"
	"fmt"
	"github.com/IBM/go-sdk-core/v4/core"
	common "github.ibm.com/CloudEngineering/go-sdk-template/common"
	"reflect"
)

// ExampleServiceV1 : No description provided (generated by Openapi Generator
// https://github.com/openapitools/openapi-generator)
//
// Version: 1.0.0
type ExampleServiceV1 struct {
	Service *core.BaseService
}

// DefaultServiceURL is the default URL to make service requests to.
const DefaultServiceURL = "http://cloud.ibm.com/mysdk/v1"

// DefaultServiceName is the default key used to find external configuration information.
const DefaultServiceName = "example_service"

// ExampleServiceV1Options : Service options
type ExampleServiceV1Options struct {
	ServiceName   string
	URL           string
	Authenticator core.Authenticator
}

// NewExampleServiceV1UsingExternalConfig : constructs an instance of ExampleServiceV1 with passed in options and external configuration.
func NewExampleServiceV1UsingExternalConfig(options *ExampleServiceV1Options) (exampleService *ExampleServiceV1, err error) {
	if options.ServiceName == "" {
		options.ServiceName = DefaultServiceName
	}

	if options.Authenticator == nil {
		options.Authenticator, err = core.GetAuthenticatorFromEnvironment(options.ServiceName)
		if err != nil {
			return
		}
	}

	exampleService, err = NewExampleServiceV1(options)
	if err != nil {
		return
	}

	err = exampleService.Service.ConfigureService(options.ServiceName)
	if err != nil {
		return
	}

	if options.URL != "" {
		err = exampleService.Service.SetServiceURL(options.URL)
	}
	return
}

// NewExampleServiceV1 : constructs an instance of ExampleServiceV1 with passed in options.
func NewExampleServiceV1(options *ExampleServiceV1Options) (service *ExampleServiceV1, err error) {
	serviceOptions := &core.ServiceOptions{
		URL:           DefaultServiceURL,
		Authenticator: options.Authenticator,
	}

	baseService, err := core.NewBaseService(serviceOptions)
	if err != nil {
		return
	}

	if options.URL != "" {
		err = baseService.SetServiceURL(options.URL)
		if err != nil {
			return
		}
	}

	service = &ExampleServiceV1{
		Service: baseService,
	}

	return
}

// SetServiceURL sets the service URL
func (exampleService *ExampleServiceV1) SetServiceURL(url string) error {
	return exampleService.Service.SetServiceURL(url)
}

// ListResources : List all resources
func (exampleService *ExampleServiceV1) ListResources(listResourcesOptions *ListResourcesOptions) (result *Resources, response *core.DetailedResponse, err error) {
	err = core.ValidateStruct(listResourcesOptions, "listResourcesOptions")
	if err != nil {
		return
	}

	pathSegments := []string{"resources"}
	pathParameters := []string{}

	builder := core.NewRequestBuilder(core.GET)
	_, err = builder.ConstructHTTPURL(exampleService.Service.Options.URL, pathSegments, pathParameters)
	if err != nil {
		return
	}

	for headerName, headerValue := range listResourcesOptions.Headers {
		builder.AddHeader(headerName, headerValue)
	}

	sdkHeaders := common.GetSdkHeaders("example_service", "V1", "ListResources")
	for headerName, headerValue := range sdkHeaders {
		builder.AddHeader(headerName, headerValue)
	}
	builder.AddHeader("Accept", "application/json")

	if listResourcesOptions.Limit != nil {
		builder.AddQuery("limit", fmt.Sprint(*listResourcesOptions.Limit))
	}

	request, err := builder.Build()
	if err != nil {
		return
	}

	var rawResponse map[string]json.RawMessage
	response, err = exampleService.Service.Request(request, &rawResponse)
	if err != nil {
		return
	}
	err = core.UnmarshalModel(rawResponse, "", &result, UnmarshalResources)
	if err != nil {
		return
	}
	response.Result = result

	return
}

// CreateResource : Create a resource
func (exampleService *ExampleServiceV1) CreateResource(createResourceOptions *CreateResourceOptions) (result *Resource, response *core.DetailedResponse, err error) {
	err = core.ValidateNotNil(createResourceOptions, "createResourceOptions cannot be nil")
	if err != nil {
		return
	}
	err = core.ValidateStruct(createResourceOptions, "createResourceOptions")
	if err != nil {
		return
	}

	pathSegments := []string{"resources"}
	pathParameters := []string{}

	builder := core.NewRequestBuilder(core.POST)
	_, err = builder.ConstructHTTPURL(exampleService.Service.Options.URL, pathSegments, pathParameters)
	if err != nil {
		return
	}

	for headerName, headerValue := range createResourceOptions.Headers {
		builder.AddHeader(headerName, headerValue)
	}

	sdkHeaders := common.GetSdkHeaders("example_service", "V1", "CreateResource")
	for headerName, headerValue := range sdkHeaders {
		builder.AddHeader(headerName, headerValue)
	}
	builder.AddHeader("Accept", "application/json")
	builder.AddHeader("Content-Type", "application/json")

	body := make(map[string]interface{})
	if createResourceOptions.ResourceID != nil {
		body["resource_id"] = createResourceOptions.ResourceID
	}
	if createResourceOptions.Name != nil {
		body["name"] = createResourceOptions.Name
	}
	if createResourceOptions.Tag != nil {
		body["tag"] = createResourceOptions.Tag
	}
	_, err = builder.SetBodyContentJSON(body)
	if err != nil {
		return
	}

	request, err := builder.Build()
	if err != nil {
		return
	}

	var rawResponse map[string]json.RawMessage
	response, err = exampleService.Service.Request(request, &rawResponse)
	if err != nil {
		return
	}
	err = core.UnmarshalModel(rawResponse, "", &result, UnmarshalResource)
	if err != nil {
		return
	}
	response.Result = result

	return
}

// GetResource : Info for a specific resource
func (exampleService *ExampleServiceV1) GetResource(getResourceOptions *GetResourceOptions) (result *Resource, response *core.DetailedResponse, err error) {
	err = core.ValidateNotNil(getResourceOptions, "getResourceOptions cannot be nil")
	if err != nil {
		return
	}
	err = core.ValidateStruct(getResourceOptions, "getResourceOptions")
	if err != nil {
		return
	}

	pathSegments := []string{"resources"}
	pathParameters := []string{*getResourceOptions.ResourceID}

	builder := core.NewRequestBuilder(core.GET)
	_, err = builder.ConstructHTTPURL(exampleService.Service.Options.URL, pathSegments, pathParameters)
	if err != nil {
		return
	}

	for headerName, headerValue := range getResourceOptions.Headers {
		builder.AddHeader(headerName, headerValue)
	}

	sdkHeaders := common.GetSdkHeaders("example_service", "V1", "GetResource")
	for headerName, headerValue := range sdkHeaders {
		builder.AddHeader(headerName, headerValue)
	}
	builder.AddHeader("Accept", "application/json")

	request, err := builder.Build()
	if err != nil {
		return
	}

	var rawResponse map[string]json.RawMessage
	response, err = exampleService.Service.Request(request, &rawResponse)
	if err != nil {
		return
	}
	err = core.UnmarshalModel(rawResponse, "", &result, UnmarshalResource)
	if err != nil {
		return
	}
	response.Result = result

	return
}

// CreateResourceOptions : The CreateResource options.
type CreateResourceOptions struct {
	// The id of the resource.
	ResourceID *string `json:"resource_id" validate:"required"`

	// The name of the resource.
	Name *string `json:"name" validate:"required"`

	// A tag value for the resource.
	Tag *string `json:"tag,omitempty"`

	// Allows users to set headers on API requests
	Headers map[string]string
}

// NewCreateResourceOptions : Instantiate CreateResourceOptions
func (*ExampleServiceV1) NewCreateResourceOptions(resourceID string, name string) *CreateResourceOptions {
	return &CreateResourceOptions{
		ResourceID: core.StringPtr(resourceID),
		Name: core.StringPtr(name),
	}
}

// SetResourceID : Allow user to set ResourceID
func (options *CreateResourceOptions) SetResourceID(resourceID string) *CreateResourceOptions {
	options.ResourceID = core.StringPtr(resourceID)
	return options
}

// SetName : Allow user to set Name
func (options *CreateResourceOptions) SetName(name string) *CreateResourceOptions {
	options.Name = core.StringPtr(name)
	return options
}

// SetTag : Allow user to set Tag
func (options *CreateResourceOptions) SetTag(tag string) *CreateResourceOptions {
	options.Tag = core.StringPtr(tag)
	return options
}

// SetHeaders : Allow user to set Headers
func (options *CreateResourceOptions) SetHeaders(param map[string]string) *CreateResourceOptions {
	options.Headers = param
	return options
}

// GetResourceOptions : The GetResource options.
type GetResourceOptions struct {
	// The id of the resource to retrieve.
	ResourceID *string `json:"resource_id" validate:"required"`

	// Allows users to set headers on API requests
	Headers map[string]string
}

// NewGetResourceOptions : Instantiate GetResourceOptions
func (*ExampleServiceV1) NewGetResourceOptions(resourceID string) *GetResourceOptions {
	return &GetResourceOptions{
		ResourceID: core.StringPtr(resourceID),
	}
}

// SetResourceID : Allow user to set ResourceID
func (options *GetResourceOptions) SetResourceID(resourceID string) *GetResourceOptions {
	options.ResourceID = core.StringPtr(resourceID)
	return options
}

// SetHeaders : Allow user to set Headers
func (options *GetResourceOptions) SetHeaders(param map[string]string) *GetResourceOptions {
	options.Headers = param
	return options
}

// ListResourcesOptions : The ListResources options.
type ListResourcesOptions struct {
	// How many items to return at one time (max 100).
	Limit *int64 `json:"limit,omitempty"`

	// Allows users to set headers on API requests
	Headers map[string]string
}

// NewListResourcesOptions : Instantiate ListResourcesOptions
func (*ExampleServiceV1) NewListResourcesOptions() *ListResourcesOptions {
	return &ListResourcesOptions{}
}

// SetLimit : Allow user to set Limit
func (options *ListResourcesOptions) SetLimit(limit int64) *ListResourcesOptions {
	options.Limit = core.Int64Ptr(limit)
	return options
}

// SetHeaders : Allow user to set Headers
func (options *ListResourcesOptions) SetHeaders(param map[string]string) *ListResourcesOptions {
	options.Headers = param
	return options
}

// Resource : A resource.
type Resource struct {
	// The id of the resource.
	ResourceID *string `json:"resource_id" validate:"required"`

	// The name of the resource.
	Name *string `json:"name" validate:"required"`

	// A tag value for the resource.
	Tag *string `json:"tag,omitempty"`

	// This is a read only string.
	ReadOnly *string `json:"read_only,omitempty"`
}


// NewResource : Instantiate Resource (Generic Model Constructor)
func (*ExampleServiceV1) NewResource(resourceID string, name string) (model *Resource, err error) {
	model = &Resource{
		ResourceID: core.StringPtr(resourceID),
		Name: core.StringPtr(name),
	}
	err = core.ValidateStruct(model, "required parameters")
	return
}

// UnmarshalResource unmarshals an instance of Resource from the specified map of raw messages.
func UnmarshalResource(m map[string]json.RawMessage, result interface{}) (err error) {
	obj := new(Resource)
	err = core.UnmarshalPrimitive(m, "resource_id", &obj.ResourceID)
	if err != nil {
		return
	}
	err = core.UnmarshalPrimitive(m, "name", &obj.Name)
	if err != nil {
		return
	}
	err = core.UnmarshalPrimitive(m, "tag", &obj.Tag)
	if err != nil {
		return
	}
	err = core.UnmarshalPrimitive(m, "read_only", &obj.ReadOnly)
	if err != nil {
		return
	}
	reflect.ValueOf(result).Elem().Set(reflect.ValueOf(obj))
	return
}

// Resources : List of resources.
type Resources struct {
	// Offset value for this portion of the resource list.
	Offset *int64 `json:"offset,omitempty"`

	// Limit value specified or defaulted in the list_resources request.
	Limit *int64 `json:"limit,omitempty"`

	// A list of resources.
	Resources []Resource `json:"resources,omitempty"`
}


// UnmarshalResources unmarshals an instance of Resources from the specified map of raw messages.
func UnmarshalResources(m map[string]json.RawMessage, result interface{}) (err error) {
	obj := new(Resources)
	err = core.UnmarshalPrimitive(m, "offset", &obj.Offset)
	if err != nil {
		return
	}
	err = core.UnmarshalPrimitive(m, "limit", &obj.Limit)
	if err != nil {
		return
	}
	err = core.UnmarshalModel(m, "resources", &obj.Resources, UnmarshalResource)
	if err != nil {
		return
	}
	reflect.ValueOf(result).Elem().Set(reflect.ValueOf(obj))
	return
}
